services:
  db:
    container_name: apprenticeship-db
    image: postgres
    environment:
      POSTGRES_USER: 2766657c
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5555:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
