server:
  port: 8090
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/apprenticeship
    username: 2766657c
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  # smtp settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: apprenticeship.server@gmail.com
    password: prbgcfuvifstymme
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      transport:
        protocol: smtp




